[package]
name = "sicas_audit"
authors = ["Ryan Goodwin <goodwir@oneonta.edu>"]
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
configparser = "3.0.0"

simple_logger = "2.1.0"
log = "0.4.14"

zip = "0.5.13"